m3dev/gokart

- Pipfile.lock
- setup.py
> Revert "read pipfile"

- gokart/__init__.py
- gokart/parameter.py
- gokart/task.py
- test/test_list_task_instance_parameter.py
- test/test_task_instance_parameter.py
Usage is
```
class SubTask(Task):
pass
class DummyTask(Task):
tasks = gokart.ListTaskInstanceParameter()
DummyTask(tasks=[SubTask(), SubTask()])
```
> Add ListTaskInstanceParameter

- README.md
- gokart/file_processor.py
Responding to the need to handle json and xml
> Support json and xml extensions

- gokart/file_processor.py
responding to #59
remove unnecessary parameter `index=False` at `dump() in JsonFileProcessor`
> removed unnecessary parameter and added accept dict

- gokart/zip_client.py
This PR uses zipfile mdule instead of shutil, because shutil fails to unzip large files.
> use zipfile

- gokart/task.py
To cache unique id once given.
> caching unique id

- gokart/task.py
https://github.com/m3dev/gokart/issues/72
> add file path in task log

- gokart/slack/slack_api.py
Fix https://github.com/m3dev/gokart/issues/77
> Fix a Slack API call.

- gokart/file_processor.py
- test/test_target.py
> support npz extension

- gokart/task.py
- test/test_task_on_kart.py
> add flag to judge to use tasks to make unique id

- setup.py
I think that applications which use gokart should fix pandas version.
> do not fix pandas version

- gokart/task.py
https://github.com/m3dev/gokart/issues/83
Output example:
- log/module_versions/Hoge_a885e05c32bed28fd86.txt
```
joblib==0.13.2
attr==19.1.0
numpy==1.16.4
tqdm==4.31.1
gcsfs==0.2.1
logging==0.5.1.2
...
```
> add module versions log

- gokart/slack/slack_api.py
slack response don't have response_metadata : https://github.com/m3dev/gokart/issues/96
> fix issue #96

- gokart/task.py
fix: https://github.com/m3dev/gokart/issues/100
> fix elasticsearch module versions

- gokart/task.py
- test/test_task_on_kart.py
- make Target to have default SingleFileTarget automatically
- filename is TASK_WORKSPACE_DIRECTORY/{directory(ies)}{file name}/{class name}_{hash}.pkl
> Generate default target automatically

- examples/sample_dynamic_requires.py
Add Eaxample.
Luigi's dynamic-dependencies is reproduced by gokart.TaskInstanceParameter :)
> Add sample_dynamic_requires example

- docs/.gitignore
this `.gitignore` looks unnecessary
> remove unused .gitignore

- gokart/file_processor.py
- gokart/task.py
- test/test_task_on_kart.py
This is a bug in modification time check logic.
For more detail, please check test cases. https://github.com/m3dev/gokart/pull/126/files#diff-55b873685a0d365f39ce80b7f7e6adddR124
> Fix modification time check logic

- examples/sample_fix_random_seed.py
- gokart/task.py
Added automatic setting of seed value according to hash, and dump of seed value.
Available in competitions like Kaggle :)
issue: https://github.com/m3dev/gokart/issues/116
> Fix random seed

- gokart/__init__.py
- test/test_explicit_bool_parameter.py
`gokart.parameter.ExplicitBoolParameter` -> `goakrt.ExplicitBoolParameter ` :)
> add ExplicitBoolParameter in __init__

- README.md
Just adding badges!  :name_badge: :name_badge:  :name_badge:
> add badges!

- README.md
> :memo: add readthedocs badge

- gokart/task.py
fix: https://github.com/vaaaaanquish/gokart-pipeliner/issues/5
> fix _get_module_versions sys.modules bugs

- examples/sample_pandas_type_check.py
- gokart/file_processor.py
- gokart/gcs_config.py
- gokart/gcs_zip_client.py
- gokart/pandas_type_config.py
- gokart/run.py
- gokart/s3_config.py
- gokart/slack/event_aggregator.py
- gokart/slack/slack_config.py
- gokart/target.py
- gokart/zip_client_util.py
- setup.py
- test/slack/test_slack_api.py
- test/test_pandas_type_config.py
- test/test_run.py
- test/testing/test_run_with_empty_data_frame.py
- yapf.ini
> Apply yapf

- README.md
I've fixed the typo at readme.
@vaaaaanquish @Hi-king @hirosassa 
Please review.
> fix readme link miss

- .github/workflows/format.yml
#161 has syntax errors
https://github.com/m3dev/gokart/actions/runs/465785631/workflow
> hotfix: ill formed format.xml

- README.md
> fix badges and cleanup whitespace

- poetry.lock
- pyproject.toml
This is small PR for dev-dependency update.
Plz review.
> Fix minor dev-dependencies

- gokart/task.py
- test/test_task_on_kart.py
> not assert task.load_data_frame(required_columns={})

- gokart/task.py
- test/test_task_on_kart.py
> Specific load

- gokart/gcs_config.py
- poetry.lock
- test/test_gcs_config.py
fixes https://github.com/m3dev/gokart/issues/187
I removed underscore function import to reduce risks of destructive change on dependent packages.
> remove underscore import on gcs_config.py

- .github/workflows/format.yml
- poetry.lock
- test/test_pandas_type_check_framework.py
SSIA
For tracking latest Luigi and other packages
https://github.com/spotify/luigi/releases/tag/3.0.3
> Package update for Luigi 3.0.3

- gokart/task.py
- test/test_task_on_kart.py
Sorry, I've created a serious bug here.
luigi's `List` is `tuple`...I'd forgotten. https://github.com/m3dev/gokart/pull/196
> fix bugs #196

- docs/index.rst
- docs/setting_task_parameters.rst
- docs/task_parameters.rst
I've fixed a small typo and added section number to make document easy to read.
Please review! @Hi-king @hirosassa @vaaaaanquish
> Fix docs typo

- docs/index.rst
- docs/setting_task_parameters.rst
- docs/task_parameters.rst
* fix typo
* fix indent level
* fix indent level
* fix indent level
* split document file for task parameter settings
* fix English
> Fix docs typo (#200)

- gokart/task.py
- poetry.lock
- pyproject.toml
- test/test_task_on_kart.py
Reverts m3dev/gokart#205
Related to https://github.com/m3dev/gokart/issues/207
> Revert "Add options to check task definition to create an output"

- gokart/build.py
- test/test_build.py
> Fix build output error when using dicts

- gokart/file_processor.py
- poetry.lock
- pyproject.toml
This PR updates dependency specification for pandas.
To follow pandas 1.2 or newer, I added `mode` variable explicitly on `to_csv` function
> follow pandas update

- docs/intro_to_gokart.rst
- gokart/build.py
- test/test_build.py
fixes https://github.com/m3dev/gokart/issues/211
Thanks to @TaylerUva
> add loglevel settings

- docs/task_on_kart.rst
- gokart/file_processor.py
- gokart/target.py
- gokart/task.py
- test/test_target.py
[What?]
I've added indexed feather file processor which is capable to store index data.
[Why?]
The existing FeatherFileProcessor cannot save index information since the index must be 0,1,2,.... when saving as feather.
Please review.
@Hi-king @hirosassa @vaaaaanquish @e-mon
> add indexedfeather file processor

- .gitignore
- test/config/test_config.ini
Recently, the unit test was not succeeding, due to settings in test_config.ini.
I've fixed the config file for the local test.
> Fix conf file for local test

- docs/intro_to_gokart.rst
- gokart/build.py
- test/test_build.py
This MR for https://github.com/m3dev/gokart/issues/209, https://github.com/m3dev/gokart/issues/229
> raise GokartbuildError on gokart.build failed

- .github/workflows/format.yml
- pyproject.toml
- yapf.ini
To simplify configs, I moved yapf configuration into pyproject.toml file.
> move yapf config into pyproject.toml

- docs/using_task_cache_collision_lock.rst
I've updated the docs of redis task lock.
Please review.
> update task lock docs

- gokart/redis_lock.py
- poetry.lock
- pyproject.toml
- test/test_redis_lock.py
- test/test_target.py
I've added test code for redis lock.
Please review!
@hirosassa @Hi-king @e-mon @kitagry @snowhork @ujiuji1259
> add redis test

- .github/workflows/format.yml
- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
- tox.ini
closes https://github.com/m3dev/gokart/issues/266
SSIA
> Python support 3.10

- docs/for_pandas.rst
- Update documentation for fail_on_empty_dump
(Close to https://github.com/m3dev/gokart/issues/281)
> Update documentation for fail_on_empty_dump

- poetry.lock
- pyproject.toml
resolve https://github.com/m3dev/gokart/issues/292
> update redis version

- gokart/s3_zip_client.py
- gokart/task.py
- gokart/testing/check_if_run_with_empty_data_frame.py
- poetry.lock
Problem: gokart could not use pandas>=1.5.0
In pandas>=1.5.0, columns cannot be declared with set().
https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#other-api-changes
However, gokart.TaskOnKart.required_columns will use set() to build pd.DataFrame when required_column is set with set() and pd.DataFrame is empty.
I changed the code to convert set to list and then build pd.DataFrame.
> set columns with list

- poetry.lock
- pyproject.toml
> fix typo in Python version

- docs/conf.py
- tox.ini
> check ruff format

- gokart/build.py
> remove debug print

- luigi.cfg
- poetry.lock
- pyproject.toml
- test/test_build.py
- tox.ini
unittest is a bit difficult to see which test was failed.
> Introduce pytest instead of unittest

- .readthedocs.yaml
Currently readthedocs build [failed](https://app.readthedocs.org/projects/gokart/builds/23201275/). So, I fixed it as following.
https://docs.readthedocs.io/en/stable/config-file/index.html
> update readthedocs setting

- docs/requirements.txt
https://app.readthedocs.org/projects/gokart/builds/26388333/
```
Theme error:
--
25 | no theme named 'sphinx_rtd_theme' found (missing theme.toml?)
```
> doc: add sphinx-rtd-theme

- gokart/build.py
- gokart/build_process_task_info.py
- pyproject.toml
- test/config/test_config.ini
- test/test_build.py
To address the common issue of identifying output locations of tasks, particularly when tasks fail and users wish to restart from the last cached output, this PR introduces an option in gokart.build to output all TaskOnKart cache file paths in an organized table or tree format. This builds on last week's update (https://github.com/m3dev/gokart/pull/423), which made task hash IDs available, by providing a structured view of all task outputs.
Added a new parameter task_dump_config to gokart.build, which allows users to specify the output format (table or tree) and output type (print or save).
Leveraged existing functionality for generating output trees and tables of task details, making it easily accessible via build arguments.
```python
class HelloWorldTask(gokart.TaskOnKart): …
```
> Add Option to Output All TaskOnKart Cache Hash and  File Paths in gokart.build

- gokart/mypy.py
> fix: fix typo of parameter handling of mypy plugin

- gokart/file_processor.py
> use engine parameter
