- docs/task_on_kart.rst
- gokart/task.py
- test/test_task_on_kart.py
https://github.com/m3dev/gokart/issues/47
usage:
```
class Hoge(gokart.TaskOnKart):
...
def run(self):
result = []
for x in self.load_generator():
result.append( proccess_file(x) )
self.dump(result)
```
`load_generator` reads the divided file into iterations.
It's effective when can't read all data to memory, because `load_generator` doesn't load all files at once.
> add load_generator

- setup.py
Since we tend to forget update version number in setup.py, I add setuptools_scm for detecting version number from git tag automatically.
> add setuptools_scm for removing verup annoying procedure

- gokart/slack/slack_api.py
- setup.py
- test/slack/test_slack_api.py
This PR migrate to slackclient v2 by minimum modifications.
I've not applied modifications show in below URL which are recommended in slackclient package.
https://github.com/slackapi/python-slackclient/blob/master/slack/web/client.py#L35
These are remaining in future task.
> minimum change for migrate slackclient v2

- gokart/file_processor.py
- test/test_target.py
At the moment, the `CsvFileProcessor.dump` method only takes a `pd.DataFrame` object as an argument. However, it should also accept `pd.Series`, since both `pd.DataFrame` and `pd.Series` classes implement the `to_csv` method.
> let CsvFileProcessor.dump accepts a pd.Series argument

- gokart/slack/slack_api.py
- test/slack/test_slack_api.py
Because of a problem with the next_cursor part of the slack api, if the number of channels exceeds 1000, all slack channels cannot be acquired.
So I implemented a process to recursively get all the slack channels.
https://api.slack.com/methods/channels.list
> fix slack class to read over 1000 channels

- gokart/file_processor.py
- setup.py
- test/test_target.py
I've added parquet extension ( `*.parquet` files) to make it easy to import data into BigQuery.
see: [BigQuery - Loading Parquet data from Cloud Storage](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet)
> Add parquet support

- gokart/gcs_config.py
- setup.py
- test/test_gcs_config.py
Now, there are many calls to Discover API. So I try to cache Discover API result.
I cannot pass test `test_get_gcs_client_without_gcs_credential_name`. Please tell me the problems.
> Add gcs discover cache

- gokart/gcs_config.py
- gokart/run.py
- gokart/s3_config.py
We already have a way to read environment variables in config > `%(hoge)s`
```
[SlackConfig]
token_name=%(SLACK_TOKEN)s
channel=lambda_test
to_user=vanquish
```
We don't need to use `os.getenv` only for Slack.
> change load Slack and S3 token method

- gokart/run.py
We were not doing gokart logging.
Because, Settings written in `core sections` can't be read.  
This is a matter of order.
```
[gokart.run] --> [part of gokart logging] --> [luigi._schedule_and_run(load log.ini)]
```
```
[core]
logging_conf_file=./log.ini
```
We need to load core.logging_conf_file in advance.
> fix gokart logger

- setup.py
We fixed python-dateutil version.  Now it is unnecessary :)
- reference 
https://github.com/spotify/luigi/issues/2662, https://github.com/spotify/luigi/blob/master/setup.py#L40
> rm require pyhton-dateutil

- gokart/task.py
- test/test_restore_task_by_id.py
- test/test_target.py
- test/test_task_on_kart.py
When a task has instances of TaskInstanceParameter, then default `requires` function returns dictionary of these instances as follows:
```python
class SomeTask(gokart.TaskOnKart):
a_task = gokart.TaskInstanceParameter()
b_task = gokart.TaskInstanceParameter()
def requires(self):
return dict(a=self.a_task, b=self.b_task)
```
> make default TaskOnKart.requires

- gokart/file_processor.py
- gokart/object_storage.py
- test/test_target.py
Since https://github.com/m3dev/gokart/pull/80, _LargeLocalFileReader has never been used.
Because ObjectStorage. is_readable_objectstorage_instance is the flag to use _LargeLocalFileReader or not.
This problem is only appears when loading files larger than 4GB on Mac.
https://stackoverflow.com/questions/31468117/python-3-can-pickle-handle-byte-objects-larger-than-4gb 
I have tested that GCS client has ability to read files with chunk.
So I have changed `ObjectStorage. is_readable_objectstorage_instance` only to  prevent S3 files from using `_LargeLocalFileReader`
> Fix to use _LargeLocalFileReader for local (and GCS) files

- gokart/file_processor.py
- gokart/task.py
- test/test_task_on_kart.py
`TaskInstanceParameter` generates a long task representation in logging. So this PR make it shorter and readable. 
In this version, `TaskInstanceParameter` generates 
```
test_task_on_kart._Task(int_param=1, task_param=test_task_on_kart._SubTask(b31b539ec58343680eab86e7e5d39c56), list_task_param=[test_task_on_kart._SubTask(b31b539ec58343680eab86e7e5d39c56), test_task_on_kart._SubTask(b31b539ec58343680eab86e7e5d39c56)])
```
> make log simple

- gokart/run.py
- gokart/slack/slack_config.py
- test/test_run.py
I would like to add config to set making dependency tree information of gokart tasks for Slack notification.
This processing sometimes take long time to make dependency tree information.
Specifically, the larger the number of dependency tasks become, the longer the time to make this information is taken.
Therefore, I add the option to select which the tree information is sent or not to Slack notification configuration.
> Add config of setting make tree info for slack notification

- gokart/task.py
- test/test_task_on_kart.py
Fixed bug that load_data_frame is currently converting index only dataframe into empty dataframe.
> allow load_data_frame to handle index only dataframe

- gokart/parameter.py
- test/test_explicit_bool_parameter.py
`luigi.BoolParameter` already has "explicit parsing" feature, but also still has implicit behavior like follows.
```shell
$ python main.py Task --param
$ python main.py Task
```
I think my PR feature is not "must-have" for Luigi, but it's "good-to-have" feature for gokart.
> Feature Request: BoolParameter which must be explicitly specified  value

- gokart/task.py
- test/test_task_on_kart.py
#6 have broken evaluation order of luigi params (https://luigi.readthedocs.io/en/stable/parameters.html#parameter-resolution-order).
> Fix evaluation order:  config file follows cmdline

- gokart/gcs_config.py
- test/test_gcs_config.py
Initializing GCSConfig is a mess process because of 
1. simply time consuming
2. noisy warning when using local default credentials (UserWarning: Your application has authenticated using end user credentials  ...)
We actually need to initialize GCSConfig just once in a whole process. So I've changed GCSConfig's behaviour as like singleton pattern.
> Change gokart.gcs_config.GCSConfig's behaviour as a singleton

- gokart/task.py
- test/test_task_on_kart.py
[What I did]
- Added `len(data.columns) == 0` condition, when considering input dataframe is empty or not (gokart/task.py L.200)
[Why]
- When loaded dataframe (which is `data` at `load_data_frame()`) has no rows but with some columns, empty dataframe with only `required_columns` columns will be returned, which may have some missing columns
Please review.
> Fixed load dataframe bug

- gokart/file_processor.py
- test/test_target.py
Feather file format is very useful for extremely huge size dataframe.
I've measured i/o speed and file size, so please consider whether or not to support it.
https://github.com/wesm/feather
I experiment with following dataframe for estimating read/write time and filesize.
```
5000 rows x 150000 columns
memory usage: 4.9 GB
```
|                  |   write ( sec ) |    read ( sec ) |  filesize   |
|:-----------------|--------:|--------:|:------------|
| pickle           |    26.5 |    18.9 | 5.03 GB     |
| feather          |    16.7 |     9.7 | 115 MB      |
| parquet          |    40.3 |   151   | 123 MB      |
| large_data_frame |   128   |    51.4 | 107 MB      |
> Feather Format FileProcessor

- README.md
- gokart/redis_lock.py
- gokart/target.py
- gokart/task.py
- setup.py
- test/test_redis_lock.py
- test/test_target.py
- test/test_task_on_kart.py
[What is this PR?]
- Adding function to handle task cache collision
[Why?]
- When multiple applications run  same task at same workspace simultaneously, task cache may collide.
- example
- Consider situation with same task AA running at application A and application B.
- In such case, when one task loads the cache while the other is writing, unexpected error may happen.
[How to overcome the problem?]
- Implement cache file lock using redis
- When gokart write/load/delete cache file, gokart will ask redis to lock file.
- When lock is taken by other application, gokart will not run write/load/delete and wait for the lock to be released.
> Handle task cache collision

- gokart/task.py
- test/test_task_on_kart.py
I've added default path for `make_large_data_frame_target()`
fix #112 
@Hi-king 
Please review.
> set default file path for make large data frame target

- gokart/file_processor.py
- setup.py
- test/test_target.py
This resolves #148 
Add `gokart.file_processor.BinaryFileProcessor` which just pass `bytes` to target file.
TargetOnKart with files with '.png' or '.jpg' extentions will automatically use `BinaryFileProcessor`
> gokart.file_processor.BinaryFileProcessor for png/jpg files

- gokart/slack/slack_api.py
Related to https://github.com/m3dev/gokart/pull/141 
Since current implementation cares Slack service related failures only, the task will be fail when network related issue occurs.
I implemented codes which catches all the exceptions.
> Improve Slack error handling

- gokart/task.py
- test/test_task_on_kart.py
Bug fix for setting redis_timeout parameters as insignificant.
@Hi-king
Please review.
> set redis_timeout parameter as siginificant=False

- gokart/slack/slack_api.py
- setup.py
- test/slack/test_slack_api.py
Slack client version 3 is available and v2 will be deprecated soon.
In this PR, migrating to `slack_sdk` package.
ref: https://slack.dev/python-slack-sdk/v3-migration/
> migrating slack_sdk from slackclient and cleanup

- docs/task_on_kart.rst
- gokart/task.py
- test/test_task_on_kart.py
introduce new feature TaskOnKart.fail_on_empty_dump, which raises error on empty dump.
Why: Empty caches sometimes hide bugs and let us spend much time debugging. This feature notice us some bugs (including wrong datasources) in the early stage.
> Careful assertion on empty dump

- gokart/task.py
- test/test_task_on_kart.py
Fixed `luigi.Parameter` --> `luigi.OptionalParameter` to suppress redundant warning messages
https://github.com/m3dev/gokart/issues/166
thx! @skokado
Please review!
@hirosassa @Hi-king @vaaaaanquish
> Suppress redundant warning messages

- gokart/s3_config.py
- test/test_s3_config.py
[What?]
I've made S3Config's S3Client as singleton.
[Why?]
The original code makes one S3Client for each loading file, which causes connection error when loading many files from S3.
Please review!
@Hi-king @hirosassa @vaaaaanquish
> make s3 config singleton

- docs/task_information.rst
- gokart/info.py
- test/test_info.py
fix: #89
For example:
```python
import luigi
import gokart
class TaskA(gokart.TaskOnKart):
param = luigi.Parameter()
def run(self):
self.dump(f'{self.param}')
class TaskB(gokart.TaskOnKart):
task = gokart.TaskInstanceParameter()
def run(self):
task = self.load('task')
self.dump(task + ' taskB')
class TaskC(gokart.TaskOnKart):
task = gokart.TaskInstanceParameter()
def run(self):
task = self.load('task')
self.dump(task + ' taskC')
class TaskD(gokart.TaskOnKart):
task1 = gokart.TaskInstanceParameter()
task2 = gokart.TaskInstanceParameter()
def run(self):
task = [self.load('task1'), self.load('task2')]
self.dump(','.join(task))
```
The more dependencies you have, the harder it is to see the tree.
```python
task = TaskD(
task1=TaskD(
task1=TaskD(task1=TaskC(task=TaskA(param='foo')), …
```
> compress info tree

- .github/workflows/test.yml
- gokart/info.py
- test/test_info.py
- An one-line fix, `set()`
- small fixes on test
- CI runs on any PRs
> 🐛 Hotfix: Should use set() for empty set declaration

- docs/setting_task_parameters.rst
- gokart/config_params.py
- test/test_config_params.py
This update allows to replace parameter name of inherited config Task, when using `@inherits_config_params` decorator.
Currently, when using `@inherits_config_params`, parameter name of inheriting config Task and decorated Task must be same. After this PR, parameter name can be replaced by passing parameter names dictionary `param_config2task` to `@inherits_config_params` decorator.
Please review!
@hirosassa @vaaaaanquish @e-mon @Hi-king
> Add parameter alias to inherits_config_params

- README.md
I've fixed the logo image url to make it visible at pypi page.
Currently, the logo is not shown at pypi.
To appear logo at pypi page, we have to convert image url link to an external link.
https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github/46875147
Please review!
@vaaaaanquish @hirosassa @Hi-king
> fix logo image url

- gokart/task.py
- poetry.lock
- pyproject.toml
- test/test_task_on_kart.py
Add a feature to create a hash of a task.
The hash is created by `cloudpickle.dumps` to the class object of a task.
Current implementation assumes that an output is determined by input parameters and requirements.
But this assumption does not work, when the implementation of a task changes.
As a results, some issues can occur.
- In local development, we need to remove output `.pkl` to rerun tasks
- `modification_time_check` can resolve this in some aspects (I like this option)
- In production with some storage (e.g. S3), backfilling or re-running can be difficult because output `.pkl` must be removed as well as local development.
So, adding task definition to hash resolves these issues and re-reruns tasks safely.
- this feature depends on `cloudpickle`
> Add options to check task definition to create an output

- gokart/utils.py
- test/config/test_config.ini
- test/test_build.py
The following error occurs when adding a configuration file with environment variables.
base.ini
```ini
[Example]
param = %(param)s
```
example.py
```pyuthon
import gokart
class Example(gokart.TaskOnKart):
param = luigi.Parameter()
def run(self):
self.dump('Hello, world!')
gokart.add_config('base.ini')
task = Example()
output = gokart.build(task)
```
erorr
```
configparser.InterpolationMissingOptionError: Bad value substitution: option 'param' in section 'Example' contains an interpolation key 'test_param' which is not a valid option name. Raw value: '%(test_param)s'
```
I think this is because the environment variables are not loaded before the parameter parsing, so I fixed `config_add` function.
Please review.
> Fix add_config behavior

- gokart/task.py
- test/test_task_on_kart.py
closes: #219 
As rerun is special parameter, it should not be implicitly cloned.
But sometimes we should pass rerun=true with clone() !
```
task = _DummyTaskRerun(a=True, rerun=True)
cloned = task.clone(_DummyTaskRerun)
cloned_with_explicit_rerun = task.clone(_DummyTaskRerun, rerun=True)
self.assertTrue(cloned.a)
self.assertFalse(cloned.rerun)  # do not clone rerun
self.assertTrue(cloned_with_explicit_rerun.a)
self.assertTrue(cloned_with_explicit_rerun.rerun)
```
> [bugfix] Should clone rerun if explicitly passed as self.clone(cls, rerun=True)

- gokart/build.py
- test/test_build.py
`gokart.build()` has a feature to disable low important logs.
However, the implementation has inconsistency, 
- logging.disable(self.level): disable any logs with level same or below the self.level
- self.logger.setLevel(self.level): enable any logs same or above the self.level
This is because logging.Logger.setLevel and logging.disable has the following difference.
> setLevel: Logging messages which **_are less severe than_** level will be ignored
> logging.disable: disable all logging calls of **_severity level and below_**
This PR fix the inconsistency by `disabling any logs with level below the self.level`
> fix LoggerConfig inconsistency bug

- docs/task_information.rst
- gokart/__init__.py
- gokart/info.py
- gokart/tree/task_info.py
- test/test_info.py
- test/tree/test_task_info.py
As discussed in https://github.com/m3dev/gokart/pull/232#issuecomment-897282110, I've refactored back end script of `make_tree_info` and moved them to `gokart.tree.task_info`.
> Refactored make_tree_info

- docs/task_information.rst
- gokart/__init__.py
- gokart/info.py
- gokart/tree/task_info.py
- gokart/tree/task_info_formatter.py
- test/tree/test_task_info.py
I've added new function `gokart.tree.task_info.dump_task_info_table()` which dumps tasks information as a pandas.DataFrame.
Issue: https://github.com/m3dev/gokart/issues/231
> Add dump_task_info_table

- gokart/run.py
- gokart/testing/check_if_run_with_empty_data_frame.py
As mentioned in https://github.com/m3dev/gokart/issues/247 , exit() may cause NameError.
I've replaced exit() with sys.exit().
Thank you for reporting the issue: @yuta100101
> replaced exit() with sys.exit()

- gokart/tree/task_info_formatter.py
- test/tree/test_task_info.py
- test/tree/test_task_info_formatter.py
I've added `requires` attribute to `TaskInfo`, so that information of `task.requires()` will be dumped to tree_info_table.
This is useful when a task requires 2 same tasks but with different parameter.
With key as index, you can get the unique_id of the two tasks separately.
```python
class _TaskInfoExampleTaskA(gokart.TaskOnKart):
def requires(self):
return dict(task1=_TaskInfoExampleTaskA(param=1), task2=_TaskInfoExampleTaskA(param=2))
```
In the above example, the requires column of tree_info_table will have dictionary with same keys as return() (i.e. task1, task2) and object of name and unique_id (i.e. RequiredTask(name, unique_id) object) as values.
In this way, we can distinguish between two tasks by key and get the unique_id.
Please review.
> Add requires to TaskInfo

- gokart/build.py
As issued in #211 , gokart was hard to debug because of less fexible logging.
With #212 log_level arg is introduced in gokart.build .
In this PR, I suggest changing default value of this log_level arg.
Of course I know there might be discussion about pros/cons of lower loglevel.
But I believe following drawback is critical one especially for first-time user of gokart.
The major drawback of suppressing logs are that we can't see traceback of failed tasks
(So we need to run tasks again with lower loglevel after facing failed tasks)
```python
class Task(gokart.TaskOnKart):
def run(self):
raise Exception()
gokart.build(Task(), log_level=logging.CRITICAL)
```
```
GokartBuildError:
===== Luigi Execution Summary =====
Scheduled 1 tasks of which:
* 1 failed:
- 1 Task(...)
This progress looks :( …
```
> change default loglevel of gokart.build as ERROR

- gokart/tree/task_info.py
- gokart/tree/task_info_formatter.py
Functions extracting task info didn't have default value for parameter ignore_task_names.
This PR adds default value `None` for them.
Please review.
> [Bugfix] Added default value for ignore_task_names parameter

- gokart/parameter.py
Hi.
Compressing strings reduces memory usage and allows [sample code](https://github.com/m3dev/gokart/issues/254#issuecomment-953476444) to run.
Please note that this is "quick" solution.
`TaskInstanceParameter.serialize` and `luigi.to_str_params` is used in a variety of ways. And it's recursive.
We will need to cache `input of TaskInstanceParameter.serialize` in the future.
> fix issue #254

- gokart/build.py
- test/test_build.py
Resolves #251 
With this fix, we can pass all the parameters which luigi.build can handle :)
> Passing additional arguments with gokart.build() (like workers=...)

- gokart/task.py
```
class PipelineTask(GokartTask):
def requires(self):
return 1.0
```
requiresメソッドでGokartTaskではない変数を返そうとすると下記のようなエラーメッセージになります。
```
luigi AttributeError: 'float' object has no attribute 'to_str_params'
```
エラーメッセージから原因がわかりずらかったので、「requiresメソッドの返り値がGokartTaskでないよ」という趣旨のValueErrorをraiseするようにしました。
> Add Error Message

- gokart/redis_lock.py
`redis_timeout` which defines the time before redis lock evaporates, cannot be shorter than 10 seconds, because redis lock is extended every 10 seconds. https://github.com/m3dev/gokart/blob/master/gokart/redis_lock.py#L58
This PR adds an assert to check that the timeout is not too short.
Please review!
> Bugfix: assert when redis_timeout is too short

- gokart/tree/task_info_formatter.py
- test/tree/test_task_info_formatter.py
solves #278 
TaskOnKart.requires() can be written as generator
```
Task:
def requires():
for ... in ...:
yield SubTas()
```
but task_info_formatter is too strict `requires()` to be `List` or `Tuple`.
This PR loosen the constraint to request `typing.Iterable`.
> Bugfix: task_info should accept generator

- gokart/tree/task_info_formatter.py
- test/tree/test_task_info.py
I've added the `cache` argument to `make_task_info_tree` to use cache in making TaskInfo tree.
This reduces time to make TaskInfo tree especially when the task tree is large.
> Use cache in make task info

- gokart/build.py
- test/test_build.py
- test/test_explicit_bool_parameter.py
- test/test_info.py
- test/test_pandas_type_check_framework.py
- test/tree/test_task_info.py
Fixes #284
* 1. reconfigure `luigi.setup_logging` configs on each setUp and tearDown
* 2. gokart.build() propagate log_level also to `luigi` namespace
https://github.com/m3dev/gokart/runs/6319432334?check_suite_focus=true
* luigi.BaseLogging has cache for disabling re-configuration
* https://github.com/spotify/luigi/blob/4d0576c7c265afcb228097af79f316ba0de0242c/luigi/setup_logging.py#L57
* So, '--log-level=CRITICAL' of each test does noting
* https://github.com/m3dev/gokart/blob/210e282303b4ca3013bd0acd781f6030547a773a/test/test_pandas_type_check_framework.py#L64
Info level logs from `luigi` namespace had been shown.
> Suppress heavy logs on test (fix #284)

- gokart/task.py
- test/test_task_on_kart.py
resolve https://github.com/m3dev/gokart/issues/286
Cannot set None for luigi.IntParameter. But `TaskOnKart.fix_random_seed_value` does this.
So following code fails
```python
task = gokart.TaskOnKart()
luigi.task_register.load_task(None, task.get_task_family(), task.to_str_params())
```
* Add above test
* Introduce magic number instead of None
> Fix `TaskOnKart.fix_random_seed_value` cannnot handle None

- gokart/config_params.py
`inherits_config_params` is not called with `TaskOnKart` **instance** but `TaskOnKart` **class itself** or its subclass.
This suppresses mypy error.
And `task_class` is better for the parameter name than `task`.
I think this change does not have a significant impact on usage because `inherits_config_params` is used as decorator.
> fix: annotation of inherits_config_params

- docs/task_on_kart.rst
- gokart/task.py
[What]
TaskOnKart.should_dump_supplementary_log_files is an option to control whether to dump supplementary files (task_log, random_seed, task_params, processing_time, module_versions) or not. Default is True, which means to dump as before.
[Why]
When each task runs, they will make 1 or more output files as defined in task.run(). Besides, 5 supplementary files (task_log, random_seed, task_params, processing_time, module_versions) will also be dumped. 
When using cloud data storage and running a large number of tasks, number of files will affect the price for data processing. This option will skip the dumping process of supplementary files to keep the price low.
Please review.
> Added should_dump_supplementary_log_files option

- poetry.lock
- pyproject.toml
- tox.ini
SSIA
Dropped Python 3.7 support because `pandas` and `numpy` dropped it and [this](https://endoflife.date/python).
> drop Python 3.7 support

- gokart/task.py
- test/test_task_on_kart.py
I've implemented `__str__` for task representations with only public parameters.
When running the task with [private parameters](https://luigi.readthedocs.io/en/stable/parameters.html#parameter-visibility), the worker now emits the logs including the raw values of private parameters.
This is caused by the implementation of `__repr__` that builds the task representation with all the significant parameters, and `str(task)` calls it because `__str__` is not implemented. It is reasonable that `__repr__` Includes all the siginificant parameters since `__repr__` should identify the task,  but I think `str(task)` should not include private parameters.
I've implemented `_get_task_string(only_public=False)` and `__str__`, and added unittest for them.
> Hide private params from logs

- docs/tutorial.rst
Fix typo (templete -> template) to be consistent with https://github.com/m3dev/cookiecutter-gokart/issues/4.
> [docs] Fix typo: templete -> template

- docs/intro_to_gokart.rst
It may seem trivial, but I found a typo in docs (intro_to_gokart.html#gokart-build) and fixed it.
> Fix typo: logginge -> logging

- .github/workflows/test.yml
- tox.ini
This PR relate with https://github.com/m3dev/kannon/pull/13. Special thanks @yokomotod.
Currently, the tox-gh-actions plugin is not recognized and all tox environments are running.
expect:
```
OK
py38: OK (35.82=setup[1.13]+cmd[34.70] seconds)
```
actual: 
```
OK
py38: OK (35.82=setup[1.13]+cmd[34.70] seconds)
py39: SKIP (0.83 seconds)
py310: OK (34.86=setup[1.20]+cmd[33.67] seconds)
py311: SKIP (0.01 seconds)
pyyapf: OK (34.55=setup[0.98]+cmd[33.57] seconds)
pyisort: OK (34.59=setup[0.99]+cmd[33.60] seconds)
pyflake8: OK (34.55=setup[1.00]+cmd[33.55] seconds)
congratulations :) (175.39 seconds)
```
> Fix CI settings

- docs/task_on_kart.rst
- gokart/file_processor.py
- test/test_file_processor.py
I've added CsvFileProcessor._encoding to allow specifying encodings when dumping in csv.
> Set encoding when saving csv

- docs/task_on_kart.rst
https://github.com/m3dev/gokart/pull/317 added the `encoding` option into `CsvFileProcessor`, but the following code in the [docs](https://github.com/m3dev/gokart/blob/master/docs/task_on_kart.rst#dump-csv-with-encoding) doesn't work.
```python
def output(self):
return self.make_target('file_name.csv', encoding='cp932')
```
In fact, we have to directly pass `CsvFileProcessor` with `encoding='cp932'` to `TaskOnKart.make_target`.
> [docs] fix csv encoding option

- docs/task_on_kart.rst
- gokart/file_processor.py
- test/test_target.py
Add `.ini` file support for `file_processor`.
We use `TextFileProcessor` for `.ini` file.
In most cases with gokart, `.ini` files are used as config files, and there are some cases that requires you to just dump `.ini` config files, like [`kannon` library](https://github.com/m3dev/kannon) development.
`configparser` or `LuigiConfigParser` are seemingly suitable choices, but their functionality are sometimes overwhelming and there should be options on how to parse the loaded config files.
So, in order to achieve these kind of requirements, we use `TextFileProcessor` for `.ini` format. The loaded files are text, so users can choose how to parse them.
> Add ini file processor

- gokart/redis_lock.py
- gokart/run_with_lock.py
- gokart/target.py
- test/test_redis_lock.py
- test/test_task_on_kart.py
This method was calling `wrap_with_run_lock()`, so I think TargetOnKart.wrap_with_run_lock  is more accurate name.
> Changed TargetOnKart.wrap_with_lock to TargetOnKart.wrap_with_run_lock 

- gokart/task.py
- gokart/task_complete_check.py
- test/test_task_on_kart.py
TaskOnKart.complete_check_at_run is a parameter to control whether to check completed cache file existence at TaskOnKArt.run().
If complete_check_at_run==True, when the worker attempt to run the task, it will check the cache file existence, and if exists, run() will be skipped.
In the original code, complete check is only evaluated at task scheduling, which is at the very beginning.
However, cache status may change when it comes to run().
This often happens when jobs in multiple nodes runs the same task.
When node1 and node2 runs the same task, the first finished node will create the completed cache, but the other node may rerun the task and recreate the same cache file.
It is okay to run same task again, but it is not efficient.
To prevent running the completed task again, I've …
> Add complete_check_at_run parameter

- gokart/build.py
- pyproject.toml
- test/test_pandas_type_check_framework.py
By default, gokart.build() resets Register. So PandasTypeConfig is also ignored.
This PR keeps PandasTypeConfig even if reset_register=True.
> gokart.build(reset_register=False) can use PandasTypeConfig

- gokart/task_complete_check.py
I've added @functools.wraps not to change wrapped function's name.
> added @functools.wraps(run_func) to task_complete_check_wrapper

- docs/using_task_cache_collision_lock.rst
- gokart/redis_lock.py
- gokart/task.py
- test/test_redis_lock.py
I've changed attribute name, since redis_fail_on_collision is difficult to understand.
> changed RedisParams.redis_fail_on_collision to RedisParams.raise_task_lock_exception_on_collision

- pyproject.toml
poetry-core is PEP 517 build backend of poetry
https://github.com/python-poetry/poetry-core
> A PEP 517 build backend implementation developed for Poetry. This project is intended to be a lightweight, fully compliant, self-contained package allowing PEP 517-compatible build frontends to build Poetry-managed projects.
We would like to try developing version of gokart
but `poetry add git+ssh://git@github.com:m3dev/gokart.git` will break original version constraints (e.g. gokart > 1.0.0) because of use of `poetry-dynamic-versioning`.
With poetry-core, we can `poetry add git+ssh://git@github.com:m3dev/gokart.git --editable`, which run  `poetry-dynamic-versioning` while installing.
I believe no side effect. Actually, current default backend is already poetry-core …
> Change build backend to poetry-core

- docs/efficient_run_on_multi_workers.rst
- gokart/task.py
- test/testing/test_run_with_empty_data_frame.py
I've changed gokart.TaskOnKart.complete_check_at_run to True by default.
This is to reduce parameter setting complexity.
reference: https://github.com/m3dev/gokart/pull/353#discussion_r1522330637
> set gokart.TaskOnKart.complete_check_at_run default True

- gokart/file_processor.py
- test/test_file_processor.py
When original DataFrame doesn't set index name, FeatherFileProcessor set index_name as 'None'. 
It is important for the compatibility, the already dumped feather file has the name `__feather_gokart_index__None`. And I think no one doesn't set `"None"` name index. :wink:
> bugfix: FeatherFileProcessor set wrong index

- gokart/build.py
- gokart/task.py
- gokart/testing/check_if_run_with_empty_data_frame.py
- gokart/tree/task_info_formatter.py
- gokart/utils.py
- gokart/workspace_management.py
- test/test_utils.py
Currently, we use `luigi.task.flatten`, but this method is not type aware (it return type is always `Unknown`. Because of this, we wrote missed type [here](https://github.com/m3dev/gokart/blob/837742d/gokart/tree/task_info_formatter.py?plain=1#L15) ( it should be `List[str]`, but `List[TaskOnKart]` ). 
So, I introduce type aware flatten method instead of `luigi.task.flatten`
> add type aware flatten method instead of `luigi.task.flatten`

- gokart/task.py
Changing priority randomly to sort the order of task scheduling randomly.
This is useful when jobs are running in parallel.
Together with the complete check function during run (complete_check_at_run; default True), it will speeds up parallel execution, because each job will run different task in different order and same tasks will not be ran.
The disadvantage is that the order of execution is scattered, so it changes a little each time when looking at the log.
> setting priority random

- gokart/file_processor.py
- gokart/utils.py
- test/test_file_processor.py
I have updated `PickleFileProcessor` to be able to load dataframes dumped in backward pandas versions.
Because the pandas dataframe dumped by pickle is not backward compatible, TargetOnKart cannot load the cache of dataframes dumped in backward pandas version.
For example, TargetOnKart in pandas 2.1.0 cannot load the large dataframe dumped in pandas 1.5.3 (error: `ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'`).
In fact,  `pd.read_pickle` can load the dataframe dumped by lower pandas version by patching [`pickle.load`](https://github.com/pandas-dev/pandas/blob/d9cdd2ee5a58015ef6f4d15c7226110c9aab8140/pandas/compat/pickle_compat.py#L212) in pandas, so we can avoid the problem by using `pd.read_pickle` instead of `dill.load`.
`pd.read_pickle` can also load any objects …
> Load DataFrame cache with backward compatibility

- gokart/file_processor.py
- gokart/utils.py
When `pd.read_pickle(file)` failed, load_dill_with_pandas_backward_compatibility() will fall back and use `dill.load(file)`.
But before loading with dill, file cursor must be rewind to the beginning.
> fix load_dill_with_pandas_backward_compatibility() bug

- docs/mypy_plugin.rst
- gokart/gcs_config.py
- gokart/mypy.py
- gokart/task.py
- gokart/testing/check_if_run_with_empty_data_frame.py
- poetry.lock
- pyproject.toml
- test/config/__init__.py
- test/config/pyproject.toml
- test/test_info.py
- test/test_mypy.py
* implement mypy plugin for `gokart.TaskOnKart`
*  This plugin checks the following when all the parameters are typed:
* The parameters passed by the constructor are valid type
* There are no missing parameters
> feat: add mypy plugin

- gokart/config_params.py
- gokart/conflict_prevention_lock/task_lock.py
- gokart/info.py
- gokart/mypy.py
- gokart/object_storage.py
- gokart/utils.py
- poetry.lock
- test/config/pyproject.toml
- test/test_mypy.py
update plugin overcomes conflicting parameter types
- following annotation is not correct when luigi type checking works after following is merged
- https://github.com/spotify/luigi/pull/3297
- make parameters return type `Any(unannotated)` and use type annotations
```python
foo: str = luigi.Parameter() # right side handled as unannotated
```
- main commit: [49d8232](https://github.com/m3dev/gokart/pull/386/commits/49d82326489ea518b50928afa980c0041053b4aa)
https://github.com/m3dev/gokart/issues/387
> feat: update plugin overcomes conflicting parameter types

- gokart/mypy.py
- test/test_mypy.py
closes: https://github.com/m3dev/gokart/issues/388
> chore: add tests for gokart parameters

- gokart/conflict_prevention_lock/task_lock_wrappers.py
- gokart/parameter.py
- gokart/slack/event_aggregator.py
- gokart/task.py
- gokart/testing/check_if_run_with_empty_data_frame.py
- gokart/utils.py
- pyproject.toml
- test/conflict_prevention_lock/test_task_lock.py
- test/test_file_processor.py
- test/test_task_instance_parameter.py
- test/test_task_on_kart.py
- test/tree/test_task_info.py
> check untyped defs

- gokart/mypy.py
- test/test_mypy.py
Currently, luigi doesn't provide py.typed. it will be released next to 3.5.1.
https://github.com/spotify/luigi/pull/3297
With the following code, we can't assume type correctly.
```python                                                                      
from luigi import Parameter
class MyTask(gokart.TaskOnKart):
param = Parameter()
```
> fix is_parameter_call

- gokart/build.py
- gokart/task.py
- poetry.lock
- pyproject.toml
- test/test_build.py
Add type to TaskOnKart. we can set type.
```python
class MyTask(gokart.TaskOnKart[str]):
def run(self):
self.dump(1)  # mypy error: expected str but got int
self.dump('1')  # mypy ok
```
> add TaskOnKart dump type

- docs/for_pandas.rst
- docs/intro_to_gokart.rst
- docs/mypy_plugin.rst
- docs/task_information.rst
- docs/task_on_kart.rst
- docs/task_parameters.rst
- docs/task_settings.rst
- gokart/parameter.py
- gokart/task.py
- poetry.lock
- test/test_build.py
- test/test_explicit_bool_parameter.py
- test/test_task_on_kart.py
Add load type for TaskOnKart.
```python
class SampleTask(gokart.TaskOnKart):
str_task: gokart.TaskOnKart[str] = gokart.TaskInstanceParameter()
int_task: gokart.TaskOnKart[int] = gokart.TaskInstanceParameter()
def requires(self):
return dict(str=self.str_task, int=self.int_task)
def run(self):
s = self.load(self.str_task)  # This type is inferred with "str"
i = self.load(self.int_task)  # This type is inferred with "int"
SampleTask(
str_task=StrTask(),  # mypy ok
int_task=StrTask(),  # mypy error: Argument "int_task" to "StrTask" has incompatible type "StrTask"; expected "TaskOnKart[int]
)
```
TODO
> Add TaskOnKart load type

- gokart/task.py
- test/test_task_on_kart.py
FIX: https://github.com/m3dev/gokart/issues/293
As mentioned in above issue, when loading 1-length dictionary with `self.load()` (no target specified), the value of dict will be loaded instead of dictionary itself.
Although this feature allows shorthand as described in the issue, the benefit is very limited and disadvantage caused by confusion is more significant.
Therefore, I want to delete this implementation.
----
This PR will cause following change.
```
class A(gokart.TaskOnKart):
task_a = gokart.TaskInstanceParameter()
def run(self):
a = self.load()
```
> Breaking change: Don't extract value from 1-length dict

- gokart/mypy.py
- test/test_mypy.py
- test/test_task_instance_parameter.py
Currently, we should write type hint for every parameters. This PR aims to infer type from Parameter names when user doesn't specify type.
```python
class MyTask(gokart.TaskOnKart):
foo = luigi.Parameter()
MyTask(foo=1)  # ok
```
```python
class MyTask(gokart.TaskOnKart):
foo = luigi.Parameter()
MyTask(foo=1)  # Argument "foo" to "MyTask" has incompatible type "str"; expected "int"
```
> feat: infer type of parameter when user doesn't specify type

- gokart/__init__.py
- gokart/build.py
- gokart/worker.py
- test/test_worker.py
* `gokart.TaskOnKart` wraps `run` function in order to inject some method when task run
* But this makes unstable on pickling  like #401 
* This PR aims to add a custom worker for gokart instead of luigi
* This PR just introduces a gokart worker which has same logic as luigi one
> [!NOTE]
> These changes does not affect any behaviors on default, because injecting the worker is an optional argument
* [410aaf1](https://github.com/m3dev/gokart/pull/402/commits/410aaf1dabb32f82c2632c827f67d9e7d29cf52d)
* copied worker from luigi and add test for worker
* do not have to read worker.py of this commit
* [3e864a0](https://github.com/m3dev/gokart/pull/402/commits/3e864a030ba741f891e5398912b7d97deb0b03bc)
* remove unused components and add type annotations
* …
> feat: use gokart worker

- gokart/__init__.py
- gokart/parameter.py
- test/test_serializable_parameter.py
* add an object parameter implementing `gokart_serialize` and `gokart_desirialize` function
* currently we need to list all the parameter to a task
* luigi.Parameters always flattend on the task
* luigi.Config also cannot be passed as a config object
* we need inherit it and use as flatten parameters
* make a set of parameters are portable to be passed to a task
The following example shows that this feature makes passing a set of parameters among tasks
```python
@dataclass(frozen=True)
class Config:
foo: int
bar: str
def gokart_serialize(self) -> str:
return json.dumps(asdict(self))
@classmethod
def gokart_deserialize(cls, s: str) -> 'Config':
return cls(**json.loads(s))
class FooTask(TaskOnKart):
config: Config = SerializableParameter(object_type=Config)
def run(self): …
```
> feat: add serializable parameter

- docs/task_parameters.rst
> docs: add description about gokart.SerializableParameter

- gokart/worker.py
- test/test_worker.py
* This PR implements an alternative way to skip a task when it is completed just before run
* This feature is currently provided by `complete_check_at_run` (#333)
* 640310c: feat: add gokart_worker configurations as same as luigi one
* 20e852f:  feat: make worker skip run when a task is completed
* `complete_check_at_run` requires to overwrite `run` function of `TaskOnKart`, which causes the issue described by #401
This PR does not affect current features because `gokart.Worker` is not used anywhere.
> feat: make worker skip running task when it is completed

- README.md
We introduce type-annotations for gokart pipelines.
Add an example how to write them on README
> docs: add an example to show how to use type-annotations on gokart

- gokart/task.py
- test/test_task_on_kart.py
We often need the task's output (cache) to examine the failed workload. Gokart (Luigi) logs the processing status of each task but we usually search for its output by listing cloud storage objects and finding the corresponding created/updated time.
Log the task ID, which is determined by parameters and used to name its cache file.
As far as I know, `__repr__` and `__str__` of `gokart.TaskOnKart` seem to be used only in logging and it does not matter to change their format. I appreciate your double-checking.
> Log task ID to locate its cache

- gokart/worker.py
- test/test_worker.py
I've changed the parameter name and description, because it may be little confusing
> changed skip_if_completed_pre_run->task_completion_check_at_run

- gokart/build.py
- test/test_build.py
This PR improves error transparency in the gokart.build process by modifying how errors are captured and reported. Instead of simply throwing a GokartBuildError when a task fails, the change includes the specific exceptions raised by each task within the error itself. This is achieved by collecting exceptions through an event handler and appending them to a GokartBuildError.
Changes:
* Updated the GokartBuildError class to include a raised_exceptions property, which is a dictionary mapping task unique IDs to lists of exceptions that occurred.
> Communicate Inner Task Exceptions as Part of GokartBuildError

- .github/workflows/test.yml
related issue: https://github.com/m3dev/gokart/issues/430
While testing on MacOS is necessary, it's more expensive than Linux testing in GitHub Actions (MacOS runners consumes 10x more minutes). 
Furthermore, MacOS is rarely used in production environments, so MacOS testing is merely to verify correct functionality in local development environments. 
Therefore, I think it's sufficient to only testing for the latest Python version.
The configuration is written in a somewhat hard-to-read manner to achieve the goal of performing minimal testing on MacOS.
Desired (but unsupported) syntax:
```
matrix:
x: [1, 2, 3, 4]
y: [a, b, c]
exclude:
- x: [1, 3]
y: [a, c]
```
Supported syntax:
```
matrix:
x: [1, 2, 3, 4]
y: [a, b, c]
exclude:
- x: 1
y: a
- x: 1
y: c
- x: 3
y: a
- x: 3
y: c
```
> add: CI on MacOS

- pyproject.toml
- It has been reported that `pytest-xdist` can cause flaky results in `pytest`.
- Removed the `-n` option from the default configuration as a temporary workaround.
- For more information, see also #436 .
> fix: fix flaky pytest behaviors

- pyproject.toml
- test/test_large_data_fram_processor.py
- test/test_s3_zip_client.py
- test/test_target.py
- test/util.py
fixes https://github.com/m3dev/gokart/issues/436
In this PR, I fixed flaky behavior of some test cases.
The cause of flakiness is that some tests handle the same directory simultaneously by the concurrent test run using `pytest-xdist` because such tests create temporary directory by using `_get_temporary_directory` function , but the directory name is fixed.
I fixed `_get_temporary_directroy` implementation and call it in `setUp` method to call it for each test runs.
> Fix flakiness on tests

- gokart/gcs_obj_metadata_client.py
- gokart/in_memory/target.py
- gokart/target.py
- gokart/task.py
- test/test_gcs_obj_metadata_client.py
This PR adds support for specifying labels when saving a task output to GCS.
Users of gokart can store some data like logs, results, parameter information etc. as cache in Google Cloud Storage(GCS).
But currently, gokart does not provide a way to add metadata labels when saving files to GCS.
So, it's so hard to track and filter the desired objects, data.
GCS has a useful field named custom object metadata, which can be added whatever you want as key-value.
So in this PR, support the way to provide this metadata to each object generated by gokart, easy to track and filter whatever you want.
- CI is passing
- Code formatting follows project standards
- Necessary tests have been added
- Existing tests pass
> Support functionalities to provide metadata as labels to object stored in GCS as cache.

- gokart/gcs_obj_metadata_client.py
https://github.com/m3dev/gokart/pull/446
At last comments by @kitagry, current implementation would violate GCS object-custom-metadata size limitation.
Thanks for @kitagry.
Change `_get_patched_obj_metadata` implementation to follow GCS object-custom-metadata size limitation.
> Fix a small bug for GCS object-custom-metadata size limitation.

- .github/workflows/test.yml
SSIA
In #433, we add CI running on macos but it made matrix representation complicated.
I found a simpler notation of this kind of CI matrix in the polars repo shown below:
https://github.com/pola-rs/polars/blob/d95e343e04d47bcbeafc815a2d9855aa5099f1bb/.github/workflows/test-python.yml#L40-L45
> simplify CI matrix

- docs/mypy_plugin.rst
- gokart/mypy.py
- test/config/__init__.py
- test/config/pyproject_disallow_missing_parameters.toml
- test/test_mypy.py
In this [discussion](https://github.com/m3dev/gokart/pull/384#discussion_r1685638052), I initially omitted handling errors for missing parameters in the task constructor because luigi.Config allows implicit parameters, making it difficult to validate them on linting
However, I occasionally forget to pass required parameters to tasks, leading to runtime errors when executing the pipeline.
This PR introduces an option for gokart mypy to raise an error when a task constructor is called without all required parameters.
Users can configure mypy to allow implicit parameter passing if needed in their project.
> feat: add mypy plugin options to handle missing paramters for a task

- gokart/build.py
- test/test_build.py
This pull request enhances error handling in `gokart` by extending the set of statuses that trigger exceptions during task builds and adding corresponding unit tests. The changes ensure more robust handling of scheduling failures and improve test coverage.
> fix: raise GokartBuildError on FAILED_AND_SCHEDULING_FAILED status

- gokart/gcs_obj_metadata_client.py
- test/test_gcs_obj_metadata_client.py
fix #466 
This pull request fix the `_get_patched_obj_metadata` method in `gokart/gcs_obj_metadata_client.py`.
In original code, we doesn't consider `str` type, so RecursionError was occurred. like #466 .
In this PR, I made the code simple and add tests in order to check the behaviors.
> fix: gcs_object_metadata_client can't handle required_tasks
